'use strict';
const D=window.REPORT_DATA;
const M={glm:'GLM',deepseek:'Flash'},P={ALL:'样本全市场',C26:'化工',C35:'专用设备',C39:'电子通信'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const num=(v,n=2,sign=false)=>v==null||!Number.isFinite(v)?'NA':(sign&&v>0?'+':'')+v.toFixed(n);
const pct=(v,n=2,sign=false)=>v==null?'NA':num(v*100,n,sign);
const mean=v=>v.length?v.reduce((a,b)=>a+b,0)/v.length:null;
const rowkey=r=>`${r.model},${r.industry},${r.arm}`;
const getGroup=(m,p,a,source=D.groups)=>source.find(r=>r.model===m&&r.industry===p&&r.arm===a);
const getUnits=r=>D.units.filter(x=>rowkey(x)===rowkey(r));
function tag(r){if(r.model==='deepseek'&&r.industry==='ALL'&&r.arm==='M3')return ['blue','D · 联合改善'];if(r.model==='deepseek'&&r.industry==='C35'&&r.arm==='M3')return ['blue','A · 经济线索'];if(r.model==='glm'&&r.industry==='ALL'&&['M0','M3'].includes(r.arm))return ['amber','B · 指标背离'];if(r.model==='deepseek'&&r.industry==='C39'&&r.arm==='M0')return ['rose','C · 基线反证'];if(r.n<3)return ['gray','仅2次有效'];return null;}
function renderTable(){const model=$('#model-filter').value,pool=$('#pool-filter').value;const rows=D.groups.filter(r=>(model==='all'||r.model===model)&&(pool==='all'||r.industry===pool));$('#row-count').textContent=`${rows.length} / 32 个设计格`;let previous='';$('#results-table tbody').innerHTML=rows.map(r=>{const group=r.model+r.industry,start=group!==previous;previous=group;const t=tag(r);return `<tr data-key="${rowkey(r)}" class="${start?'group-start':''}"><td><button class="row-link" data-detail="${rowkey(r)}">${M[r.model]} / ${r.industry}</button></td><td>${r.arm}</td><td>${r.n}</td><td>${num(r.rank_ic,4)}</td><td>${num(r.rank_icir,3)}</td><td>${pct(r.net_cagr)}</td><td class="${r.excess_cagr==null?'na':r.excess_cagr>0?'pos':'neg'}">${pct(r.excess_cagr,2,true)}</td><td>${num(r.sharpe)}</td><td>${pct(r.max_drawdown)}</td><td>${pct(r.turnover_two_sided_daily_mean)}</td><td>${t?`<span class="annotation ${t[0]}">${t[1]}</span>`:''}</td></tr>`}).join('');}
function openDetail(key){const r=D.groups.find(x=>rowkey(x)===key);if(!r)return;$('#detail-title').textContent=`${M[r.model]} / ${P[r.industry]} / ${r.arm}`;const units=getUnits(r);let s='';if(!r.n){s='<div class="callout">该组没有完整样本外评价。原始实验中 Flash 的 ALL / C26 的 M3 均在执行过程中失败；不能把保留的部分候选当作完成结果，也不能填成零收益。</div>';}else{s=`<div class="callout">${r.n} 次有效重复，平均 IC <b>${num(r.rank_ic,4)}</b>，平均净年化 <b>${pct(r.net_cagr)}%</b>，平均年化超额 <b>${pct(r.excess_cagr,2,true)} pp</b>。下面每一行是一套独立生成、筛选、冻结后的组合。</div><div class="table-scroll"><table><thead><tr><th>重复</th><th>冻结因子数</th><th>IC</th><th>ICIR</th><th>净年化 %</th><th>超额 pp</th><th>回撤 %</th><th>换手 %</th></tr></thead><tbody>${units.map(x=>`<tr><td>第 ${x.repeat} 次</td><td>${x.factor_count}</td><td>${num(x.rank_ic,4)}</td><td>${num(x.rank_icir,3)}</td><td>${pct(x.net_cagr)}</td><td>${pct(x.excess_cagr,2,true)}</td><td>${pct(x.max_drawdown)}</td><td>${pct(x.turnover_two_sided_daily_mean)}</td></tr>`).join('')}</tbody></table></div><p class="footnote">超额范围 ${pct(r.excess_min,2,true)} 至 ${pct(r.excess_max,2,true)} pp；${r.positive_excess_runs}/${r.n} 次跑赢基准。三次重复共用 2017 年市场，不是三个独立年份。</p>`;}$('#detail-body').innerHTML=s;$('#detail-dialog').showModal();}
$('#model-filter').addEventListener('change',renderTable);$('#pool-filter').addEventListener('change',renderTable);$('#reset-table').addEventListener('click',()=>{$('#model-filter').value='all';$('#pool-filter').value='all';renderTable()});$('#results-table').addEventListener('click',e=>{const row=e.target.closest('[data-key]');if(row)openDetail(row.dataset.key)});$$('[data-focus]').forEach(el=>el.addEventListener('click',()=>{const [m,p,a]=el.dataset.focus.split(',');$('#model-filter').value=m;$('#pool-filter').value=p;renderTable();const tr=$(`[data-key="${el.dataset.focus}"]`);tr?.classList.add('selected');tr?.scrollIntoView({block:'nearest',behavior:'smooth'});openDetail(el.dataset.focus)}));$('#close-detail').addEventListener('click',()=>$('#detail-dialog').close());$('#detail-dialog').addEventListener('click',e=>{if(e.target===$('#detail-dialog')){const b=e.target.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)e.target.close()}});renderTable();

const ARMS=['M0','M1','M2','M3'],POOLS=['ALL','C26','C35','C39'],MODELS=['glm','deepseek'];
const AC={M0:'#64748b',M1:'#236dae',M2:'#b66b1c',M3:'#087e7b'},MC={glm:'#236dae',deepseek:'#b66b1c'};
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const svgStart=(w,h,title)=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(title)}"><title>${esc(title)}</title>`;
const txt=(x,y,s,anchor='start',color='#596b7f',size=13)=>`<text x="${x}" y="${y}" text-anchor="${anchor}" fill="${color}" font-size="${size}">${esc(s)}</text>`;
const ln=(x1,y1,x2,y2,c='#dce4ed',w=1)=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${c}" stroke-width="${w}"/>`;
const htmlTable=(heads,rows)=>`<table><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
function completeRepeat(m,p,r){return ARMS.every(a=>D.units.some(x=>x.model===m&&x.industry===p&&x.arm===a&&x.repeat===r))}
function currentContrasts(){const comp=$('#contrast-select').value,metric=$('#contrast-metric').value,balanced=$('#contrast-sample').value==='balanced';return MODELS.flatMap(m=>POOLS.map(pool=>{const pairs=D.pairs.filter(r=>r.model===m&&r.industry===pool&&r.comparison===comp&&(!balanced||completeRepeat(m,pool,r.repeat)));const v=pairs.map(x=>x['delta_'+metric]*(metric==='net_cagr'?100:1));return {model:m,pool,pairs,values:v,n:v.length,avg:mean(v),positive:v.filter(x=>x>0).length}}))}
const contrastCopy={"M1-M0": "原生经验检索未建立普遍优势：8个层面中仅1个平均IC改善，6个平均净收益改善；24次配对中IC为5次改善、净收益为12次改善。预测信息与持仓收益的变化方向不同，不能直接把更高净收益解释成更强预测。", "M2-M1": "结构化证据的效果混合：平均IC在4/8个层面改善，净收益在4/8个层面改善；24次配对分别13次和10次改善。Flash化工同时改善预测与净收益，而GLM化工和Flash专用设备的平均收益下降。", "M3-M2": "摘要增量具有明显异质性：5/8个层面平均IC改善、5/8个层面平均净收益改善；24次配对分别14次和16次改善。Flash全市场两项均3/3改善；GLM化工、GLM专用设备的平均IC与净收益均下降。", "M3-M0": "完整Memory的预测优势较弱：仅Flash全市场与化工的平均IC高于M0；净收益在6/8个层面改善。24次配对中IC改善8次、净收益改善16次。Flash电子通信的IC和净收益均3/3下降，是必须保留的反向证据。", "M3-M1": "结构化证据加摘要的联合增量：6/8个层面平均IC改善，6/8个层面平均净收益改善；24次配对分别15次和14次改善。它包含两项输入变化与额外推理资源，不能单独归因于摘要内容。"};
function renderContrast(){const rows=currentContrasts(),metric=$('#contrast-metric').value,valid=rows.filter(x=>x.n),n=valid.reduce((a,r)=>a+r.n,0),wins=valid.reduce((a,r)=>a+r.positive,0),groupwins=valid.filter(r=>r.avg>0).length;$('#contrast-summary').innerHTML=`<span><b>${groupwins}/${valid.length}</b> 层面均值改善</span><span><b>${wins}/${n}</b> 配对重复改善</span><span>${metric==='net_cagr'?'净年化收益差 / pp':metric==='rank_ic'?'Rank IC 差':'未年化 ICIR 差'}</span>`;const w=940,h=402,left=135,right=740,top=51,rh=38;const all=valid.flatMap(x=>x.values),max=Math.max(...all.map(Math.abs),.0001)*1.14,x=v=>(left+right)/2+v/max*(right-left)/2;let out=svgStart(w,h,'Memory配对差异，每个圆为单次配对，菱形为均值');for(let j=-2;j<=2;j++){const v=max*j/2;out+=ln(x(v),27,x(v),top+7*rh+19,j===0?'#91a2b6':'#e6edf3',j===0?1.5:1)+txt(x(v),h-27,num(v,metric==='net_cagr'?1:3),'middle');}out+=txt(left,15,'较低', 'start')+txt(right,15,'较高','end')+txt(782,15,'均值 / 改善次数');rows.forEach((r,i)=>{const y=top+i*rh,col=MC[r.model];out+=txt(8,y+5,`${M[r.model]} / ${r.pool}`,'start','#192e47',14);if(!r.n){out+=txt(780,y+5,'NA · 无完整配对');return}const lo=Math.min(...r.values),hi=Math.max(...r.values);out+=ln(x(lo),y,x(hi),y,col,2);r.values.forEach((v,j)=>out+=`<circle cx="${x(v)}" cy="${y+(j-1)*5}" r="4.5" fill="white" stroke="${col}" stroke-width="1.5"><title>重复${r.pairs[j].repeat}: ${num(v,metric==='net_cagr'?3:5,true)}</title></circle>`);const a=x(r.avg);out+=`<path d="M${a},${y-7}l7,7 -7,7 -7,-7Z" fill="${col}"/>`+txt(780,y+5,`${num(r.avg,metric==='net_cagr'?3:5,true)} · ${r.positive}/${r.n}`,'start','#192e47',14);});out+=txt(465,h-3,'细线连接该层面的最小和最大配对值，不表示置信区间','middle','#596b7f',12)+'</svg>';$('#contrast-chart').innerHTML=out;$('#contrast-reading').innerHTML=`<strong>研究判断：</strong>${contrastCopy[$('#contrast-select').value]}${$('#contrast-sample').value==='balanced'?'<p>当前96格全部完整，两种样本口径一致，每个模型×股票池均有三对。</p>':''}`;$('#contrast-table').innerHTML=htmlTable(['模型 / 池','配对 n','平均差','最小差','最大差','改善次数'],rows.map(r=>[`${M[r.model]} / ${r.pool}`,r.n,num(r.avg,metric==='net_cagr'?3:5,true),r.n?num(Math.min(...r.values),metric==='net_cagr'?3:5,true):'NA',r.n?num(Math.max(...r.values),metric==='net_cagr'?3:5,true):'NA',r.n?`${r.positive}/${r.n}`:'NA']));}
['#contrast-select','#contrast-metric','#contrast-sample'].forEach(id=>$(id).addEventListener('change',renderContrast));renderContrast();
$('#model-table').innerHTML=htmlTable(['模型 / 配置','共同格 n','IC','ICIR','净年化 %','超额 pp','Sharpe','平均回撤 %','换手 %'],MODELS.map(m=>{const r=D.models[m];return [m==='glm'?'GLM · low':'Flash · thinking disabled',r.n,num(r.rank_ic,5),num(r.rank_icir,5),pct(r.net_cagr,3),pct(r.excess_cagr,3,true),num(r.sharpe,3),pct(r.max_drawdown,3),pct(r.turnover_two_sided_daily_mean,3)]}));
$('#model-pool-table').innerHTML=htmlTable(['股票池','共同格 n','ΔIC','Δ净年化 pp'],POOLS.map(p=>{const a=D.modelpools.find(r=>r.model==='glm'&&r.industry===p),b=D.modelpools.find(r=>r.model==='deepseek'&&r.industry===p);return [p,a.n,num(b.rank_ic-a.rank_ic,5,true),pct(b.net_cagr-a.net_cagr,3,true)]}));
const industryCopy={"ALL": "Flash M3 的 IC=0.06403、ICIR=0.535，净年化−13.24%，超额+2.40 pp；相对M2，三次IC与净收益全部改善。相对M0虽三次净收益都改善，IC仅1/3改善，预测优势仍有重复差异。GLM M0的IC最高，M3净收益较好但相对M0仅1/3改善。", "C26": "GLM M1 平均超额+2.43 pp，M2、M3均转负；M3相对M2平均IC和净收益均下降。Flash M3超额−1.38 pp，较M0净收益三次均改善，仍未跑赢基准；相对M2平均IC略降，净收益略升。", "C35": "Flash M3三次超额均为正，平均+7.09 pp，但净年化仍为−14.17%。M3相对M2净年化平均增加6.15 pp，三次中有一次下降；相对M0三次净收益均改善。GLM四组平均超额约+1.05至+1.62 pp，组间差距较小。", "C39": "Flash M0在IC和净收益上均优于M1–M3，M3相对M0三次均退步；GLM M1预测较强，但四组平均超额均为负。M3相对M2的局部IC改善并未形成一致净收益优势。"};
function industryBars(metric){const pool=$('#industry-select').value,source=$('#industry-sample').value==='balanced'?D.balanced:D.groups,w=620,h=275,left=53,right=604,top=29,bottom=204;const vals=MODELS.flatMap(m=>ARMS.map(a=>getGroup(m,pool,a,source))),values=vals.filter(r=>r.n).map(r=>r[metric]*(metric==='excess_cagr'?100:1));let min=Math.min(0,...values),max=Math.max(0,...values);if(max-min<.00001){min=-1;max=1}const range=max-min;min-=range*.15;max+=range*.18;const yy=v=>bottom-(v-min)/(max-min)*(bottom-top);let s=svgStart(w,h,`${P[pool]} ${metric==='rank_ic'?'Rank IC':'年化超额'}`);for(let i=0;i<=4;i++){const v=min+(max-min)*i/4;s+=ln(left,yy(v),right,yy(v))+txt(left-6,yy(v)+4,num(v,metric==='rank_ic'?3:1),'end');}s+=ln(left,yy(0),right,yy(0),'#8d9caf',1.3);ARMS.forEach((a,i)=>{const cx=left+(i+.5)*(right-left)/4;MODELS.forEach((m,j)=>{const r=getGroup(m,pool,a,source),x=cx-31+j*32;if(r.n){const v=r[metric]*(metric==='excess_cagr'?100:1),z=yy(v),zero=yy(0);s+=`<rect x="${x}" y="${Math.min(z,zero)}" width="27" height="${Math.max(1,Math.abs(z-zero))}" fill="${MC[m]}" rx="2"><title>${M[m]} ${a}: ${num(v,metric==='rank_ic'?4:2)}, n=${r.n}</title></rect>`+txt(x+13,z+(v>=0?-7:16),num(v,metric==='rank_ic'?3:2),'middle',MC[m],12);}else{s+=txt(x+13,yy(0)-8,'NA','middle','#6c7887',12)}s+=txt(x+13,bottom+35,'n='+r.n,'middle','#6c7887',12)});s+=txt(cx,bottom+19,a,'middle','#192e47',14)});s+=txt(190,h-5,'■ GLM','middle',MC.glm,13)+txt(410,h-5,'■ Flash','middle',MC.deepseek,13)+'</svg>';return s;}
function renderIndustry(){$('#industry-ic').innerHTML=industryBars('rank_ic');$('#industry-return').innerHTML=industryBars('excess_cagr');$('#industry-reading').innerHTML=`<strong>${P[$('#industry-select').value]}：</strong>${industryCopy[$('#industry-select').value]}${$('#industry-sample').value==='balanced'?'<p>当前四组共同样本与全部有效样本一致，每组均为三次重复。</p>':''}`;}['#industry-select','#industry-sample'].forEach(id=>$(id).addEventListener('change',renderIndustry));renderIndustry();
function scatter(){const w=620,h=320,l=57,r=588,t=23,b=252,x=v=>l+v/.075*(r-l),y=v=>b-(v+8)/17*(b-t);let s=svgStart(w,h,'组均值IC与成本后超额散点图');for(const v of [-6,-3,0,3,6,9])s+=ln(l,y(v),r,y(v),v===0?'#8b9cb0':'#e3eaf1')+txt(l-8,y(v)+4,v,'end');for(const v of [0,.02,.04,.06])s+=ln(x(v),t,x(v),b)+txt(x(v),b+20,v.toFixed(2),'middle');s+=txt(l,t-9,'年化超额 / pp','start','#596b7f',12)+txt(r,b+20,'IC','end');D.groups.filter(a=>a.n).forEach(a=>{const xx=x(a.rank_ic),yy=y(a.excess_cagr*100),tip=`${M[a.model]} / ${a.industry} / ${a.arm}, IC ${num(a.rank_ic,4)}, 超额 ${pct(a.excess_cagr,2,true)}pp, n=${a.n}`;s+=a.model==='glm'?`<circle cx="${xx}" cy="${yy}" r="5.7" fill="${AC[a.arm]}" fill-opacity=".8" stroke="white"><title>${tip}</title></circle>`:`<path d="M${xx},${yy-7}l7,7 -7,7 -7,-7Z" fill="${AC[a.arm]}" fill-opacity=".8" stroke="white"><title>${tip}</title></path>`;if(a.model==='deepseek'&&a.industry==='C35'&&a.arm==='M3')s+=txt(xx+12,yy-10,'Flash C35 M3','start',AC.M3,12)});ARMS.forEach((a,i)=>s+=txt(115+i*120,308,'■ '+a,'middle',AC[a]));$('#scatter-chart').innerHTML=s+'</svg>';}scatter();
function costChart(){const w=620,h=320,l=57,r=579,t=28,b=250,x=v=>l+v/20*(r-l),y=v=>b-(v+4.7)/7.7*(b-t);let s=svgStart(w,h,'完整48格成本敏感性');for(const v of [-4,-2,0,2])s+=ln(l,y(v),r,y(v),v===0?'#8b9caf':'#e3eaf1')+txt(l-8,y(v)+4,v,'end');[0,5,10,20].forEach(v=>s+=txt(x(v),b+20,v,'middle'));MODELS.forEach(m=>{const pts=D.models[m].costs.map((v,i)=>[x([0,5,10,20][i]),y(v*100)]);s+=`<polyline points="${pts.map(a=>a.join(',')).join(' ')}" fill="none" stroke="${MC[m]}" stroke-width="2.5"/>`;pts.forEach(([xx,yy],i)=>s+=`<circle cx="${xx}" cy="${yy}" r="4" fill="${MC[m]}"><title>${M[m]}, 每边${[0,5,10,20][i]}bps, 超额${pct(D.models[m].costs[i],3,true)}pp</title></circle>`);});s+=txt(l,15,'年化超额 / pp','start','#596b7f',12)+txt(r,b+40,'每边成本 / bps','end')+txt(155,308,'■ GLM','middle',MC.glm)+txt(320,308,'■ Flash','middle',MC.deepseek);$('#cost-chart').innerHTML=s+'</svg>';}costChart();
$('#decomposition-table').innerHTML=htmlTable(['模型 / 池','配对 n','Δ零成本超额','Δ成本情景影响','Δ10bps净超额','Δ日双边换手'],D.contrasts.filter(r=>r.comparison==='M3-M2').map(r=>[`${M[r.model]} / ${r.industry}`,r.n,pct(r.delta_gross_excess_cagr,3,true),pct(r.delta_cost_impact,3,true),pct(r.delta_net_cagr,3,true),pct(r.delta_turnover_two_sided_daily_mean,2,true)]));
const median=a=>{const v=[...a].sort((a,b)=>a-b),n=v.length;return n%2?v[(n-1)/2]:(v[n/2-1]+v[n/2])/2};
function renderCurve(){const m=$('#curve-model').value,p=$('#curve-pool').value,relative=$('#curve-kind').value==='relative',arms=$$('.arm-checks input:checked').map(x=>x.value);const sets=arms.map(a=>({a,rows:D.units.filter(r=>r.model===m&&r.industry===p&&r.arm===a).map(r=>{const c=D.curves[`${m}/${p}/${a}/${r.repeat}`];return {repeat:r.repeat,v:c.net.map((v,i)=>relative?v/c.benchmark[i]:v)}})}));const all=sets.flatMap(s=>s.rows.flatMap(r=>r.v));if(!all.length){$('#curve-chart').innerHTML='<p class="empty">当前没有可显示的完整净值。请选择至少一个有结果的组。</p>';$('#curve-legend').innerHTML='';return}const w=1120,h=340,l=65,r=1095,t=22,b=286;let min=Math.min(1,...all),max=Math.max(1,...all);const range=Math.max(.01,max-min);min-=range*.08;max+=range*.08;const x=i=>l+i/(D.dates.length-1)*(r-l),y=v=>b-(v-min)/(max-min)*(b-t);let s=svgStart(w,h,`${M[m]} ${P[p]} ${relative?'相对':'策略'}净值：细线为重复，粗线为中位数`);for(let i=0;i<=4;i++){const v=min+(max-min)*i/4;s+=ln(l,y(v),r,y(v))+txt(l-8,y(v)+4,num(v,2),'end')};s+=ln(l,y(1),r,y(1),'#8b9caf',1.3);[[0,'2017.01'],[60,'04'],[121,'07'],[183,'10'],[243,'12月底']].forEach(([i,v])=>s+=txt(x(i),b+23,v,'middle'));sets.forEach(({a,rows})=>{rows.forEach(row=>s+=`<polyline points="${row.v.map((v,i)=>`${x(i).toFixed(2)},${y(v).toFixed(2)}`).join(' ')}" fill="none" stroke="${AC[a]}" opacity=".35" stroke-width="1"><title>${a} 重复${row.repeat}</title></polyline>`);if(rows.length){const med=D.dates.map((_,i)=>median(rows.map(row=>row.v[i])));s+=`<polyline points="${med.map((v,i)=>`${x(i).toFixed(2)},${y(v).toFixed(2)}`).join(' ')}" fill="none" stroke="${AC[a]}" stroke-width="2.6"><title>${a} 逐日中位数</title></polyline>`}});$('#curve-chart').innerHTML=s+'</svg>';$('#curve-legend').innerHTML=sets.map(({a,rows})=>`<span style="color:${AC[a]}">■ ${a} · n=${rows.length}${!rows.length?'（无完整结果）':''}</span>`).join('');}
['#curve-model','#curve-pool','#curve-kind'].forEach(id=>$(id).addEventListener('change',renderCurve));$$('.arm-checks input').forEach(e=>e.addEventListener('change',renderCurve));renderCurve();
$('#factor-table').innerHTML=htmlTable(['模型','组','冻结记录数','训练 IC均值','验证 IC均值','测试 IC均值','测试 IC>0'],D.factors.map(r=>[M[r.model],r.arm,r.n,num(r.train,4),num(r.validation,4),num(r.test,4),`${r.positive}/${r.n}`]));
$('#source-hash').textContent='主输入 SHA256：'+D.meta.sha256;
